services:
    displaycoffee.khyeras.utilities:
        class: displaycoffee\khyeras\utilities\utilities

    displaycoffee.khyeras.listener:
        class: displaycoffee\khyeras\event\main_listener
        arguments:
            - '@displaycoffee.khyeras.page_info'
            - '@displaycoffee.khyeras.global_member_info'
            - '@displaycoffee.khyeras.member_character_info'
            - '@displaycoffee.khyeras.topic_character_info'
            - '@displaycoffee.khyeras.add_to_group'
        tags:
            - { name: event.listener }

    displaycoffee.khyeras.page_info:
        class: displaycoffee\khyeras\core\page_info
        arguments:
            - '@template'
            - '@user'
            - '@dbal.conn'
            - '@displaycoffee.khyeras.utilities'
            - '%core.table_prefix%'
            - '%core.php_ext%'

    displaycoffee.khyeras.global_member_info:
        class: displaycoffee\khyeras\core\global_member_info
        arguments:
            - '@template'
            - '@user'
            - '@dbal.conn'
            - '@profilefields.manager'
            - '@profilefields.lang_helper'
            - '@displaycoffee.khyeras.utilities'
            - '%core.table_prefix%'

    displaycoffee.khyeras.add_to_group:
        class: displaycoffee\khyeras\core\add_to_group
        arguments:
            - '@dbal.conn'
            - '%core.table_prefix%'

    displaycoffee.khyeras.member_character_info:
        class: displaycoffee\khyeras\core\member_character_info
        arguments:
            - '@template'
            - '@displaycoffee.khyeras.utilities'

    displaycoffee.khyeras.topic_character_info:
        class: displaycoffee\khyeras\core\topic_character_info
        arguments:
            - '@template'
            - '@displaycoffee.khyeras.utilities'
