services:
    displaycoffee.khyeras.listener:
        class: displaycoffee\khyeras\event\main_listener
        arguments:
            - '@template'
            - '@user'
            - '@dbal.conn'
            - '@profilefields.manager'
            - '@profilefields.lang_helper'
            - '%core.php_ext%'
        tags:
            - { name: event.listener }
