services:
    displaycoffee.extendautogroups.autogroups.type.account_type:           # change this for your extension
        class: displaycoffee\extendautogroups\conditions\type\account_type # change this for your extension
        shared: false
        arguments:
            - '@service_container'
            - '@dbal.conn'
            - '@language'
            - '%core.table_prefix%autogroups_rules'
            - '%core.table_prefix%autogroups_types'
            - '%core.root_path%'
            - '%core.php_ext%'
        tags:
            - { name: phpbb.autogroups.type }

    displaycoffee.extendautogroups.listener:
        class: displaycoffee\extendautogroups\event\listener
        arguments:
            - '@?phpbb.autogroups.manager'   # The ? defines this as an optional dependency
        tags:
            - { name: event.listener }
