imports:
    - { resource: tables.yml }

services:
    displaycoffee.khyeras.utilities:
        class: displaycoffee\khyeras\utilities\utilities
        arguments:
            - '%displaycoffee.khyeras.tables.groups%'
            - '%displaycoffee.khyeras.tables.pages%'
            - '%displaycoffee.khyeras.tables.users%'
            - '%displaycoffee.khyeras.tables.user_group%'

    displaycoffee.khyeras.listener:
        class: displaycoffee\khyeras\event\main_listener
        arguments:
            - '@displaycoffee.khyeras.account_to_group'
            - '@displaycoffee.khyeras.character_info_profile'
            - '@displaycoffee.khyeras.character_info_viewtopic'
            - '@displaycoffee.khyeras.global_info'
        tags:
            - { name: event.listener }

    displaycoffee.khyeras.global_info:
        class: displaycoffee\khyeras\core\global_info
        arguments:
            - '@template'
            - '@user'
            - '@dbal.conn'
            - '@profilefields.manager'
            - '@profilefields.lang_helper'
            - '@displaycoffee.khyeras.utilities'
            - '%core.table_prefix%'
            - '%core.php_ext%'

    displaycoffee.khyeras.account_to_group:
        class: displaycoffee\khyeras\core\account_to_group
        arguments:
            - '@dbal.conn'
            - '@displaycoffee.khyeras.utilities'

    displaycoffee.khyeras.character_info_profile:
        class: displaycoffee\khyeras\core\character_info_profile
        arguments:
            - '@template'
            - '@displaycoffee.khyeras.utilities'

    displaycoffee.khyeras.character_info_viewtopic:
        class: displaycoffee\khyeras\core\character_info_viewtopic
        arguments:
            - '@template'
            - '@displaycoffee.khyeras.utilities'
