services:
    displaycoffee.khyeras.utilities:
        class: displaycoffee\khyeras\utilities\utilities

    displaycoffee.khyeras.listener:
        class: displaycoffee\khyeras\event\main_listener
        arguments:
            - '@template'
            - '@user'
            - '@dbal.conn'
            - '@profilefields.manager'
            - '@profilefields.lang_helper'
            - '@phpbb.pages.operator'
            - '@displaycoffee.khyeras.page_info'
            - '%core.php_ext%'
        tags:
            - { name: event.listener }

    displaycoffee.khyeras.page_info:
        class: displaycoffee\khyeras\core\page_info
        arguments:
            - '@dbal.conn'
            - '%core.table_prefix%'
