services:
    foo.bar.autogroups.type.example:           # change this for your extension
        class: foo\bar\conditions\type\example # change this for your extension
        scope: prototype
        arguments:
            - @service_container
            - @dbal.conn
            - @user
            - %core.table_prefix%autogroups_rules
            - %core.table_prefix%autogroups_types
            - %core.root_path%
            - %core.php_ext%
        tags:
            - { name: phpbb.autogroups.type }

    foo.bar.listener:
        class: foo\bar\event\listener
        arguments:
            - @?phpbb.autogroups.manager   # The ? defines this as an optional dependency
        tags:
            - { name: event.listener }

